import Head from "next/head";
import { Box, Input, InputGroup, InputRightElement } from "@chakra-ui/react";
import { useDispatch, useSelector } from "react-redux";
import { useForm } from "react-hook-form";
import { BiSearchAlt } from "react-icons/bi";
import { getWords } from "@/redux/features/wordSlice";
import Navbar from "./components/Navbar";

export default function Home() {
  const dispatch = useDispatch();
  const { register, watch, handleSubmit } = useForm();

  const words = useSelector((state) => state.word);
  console.log(words);

  const onSubmit = () => {
    dispatch(getWords(watch("word")));
  };
  return (
    <>
      <Head>
        <title>Dictionary App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Box p={2} maxW={["100%", "2xl"]} m="auto">
          <form onSubmit={handleSubmit(onSubmit)}>
            <Box mx={4} my={2}>
              <InputGroup>
                <InputGroup>
                  <InputRightElement
                    pointerEvents="none"
                    children={<BiSearchAlt color="gray.300" />}
                  />
                  <Input
                    {...register("word")}
                    type="text"
                    placeholder="Search keywords here"
                    colorScheme="twitter"
                  />
                </InputGroup>
              </InputGroup>
            </Box>
          </form>
        </Box>
      </main>
    </>
  );
}
